package cii

import (
	"math"
	"strings"

	"github.com/invopop/gobl/bill"
	"github.com/invopop/gobl/catalogues/cef"
	"github.com/invopop/gobl/catalogues/iso"
	"github.com/invopop/gobl/catalogues/untdid"
	"github.com/invopop/gobl/cbc"
	"github.com/invopop/gobl/l10n"
	"github.com/invopop/gobl/num"
	"github.com/invopop/gobl/org"
	"github.com/invopop/gobl/tax"
)

func goblAddLines(in *Transaction, out *bill.Invoice, taxMap map[string]*taxCategoryInfo) error {
	items := in.Lines
	lines := make([]*bill.Line, 0, len(items))

	for _, it := range items {
		price, err := num.AmountFromString(it.Agreement.NetPrice.Amount)
		if err != nil {
			return err
		}

		// BT-148: Price base quantity — normalize unit price
		if bq := it.Agreement.NetPrice.BaseQuantity; bq != nil && bq.Amount != "" {
			baseQuantity, err := num.AmountFromString(bq.Amount)
			if err != nil {
				return err
			}
			if !baseQuantity.IsZero() {
				precision := calculateRequiredPrecision(price, baseQuantity)
				price = price.RescaleUp(precision).Divide(baseQuantity)
			}
		}

		l := &bill.Line{
			// Index is generated by GOBL
			//If Quantity is not present, assume 1
			Quantity: num.MakeAmount(1, 0),
			Item: &org.Item{
				Name:  strings.TrimSpace(it.Product.Name),
				Price: &price,
			},
			Taxes: tax.Set{
				{
					Category: cbc.Code(it.TradeSettlement.ApplicableTradeTax[0].TypeCode),
				},
			},
		}

		if it.Quantity != nil && it.Quantity.Quantity != nil {
			l.Quantity, err = num.AmountFromString(it.Quantity.Quantity.Amount)
			if err != nil {
				return err
			}
		}

		if it.Quantity.Quantity.UnitCode != "" {
			u := cbc.Code(it.Quantity.Quantity.UnitCode)
			l.Item.Unit = goblUnitFromUNECE(u)
		}

		if it.Product.SellerAssignedID != nil {
			l.Item.Ref = cbc.Code(*it.Product.SellerAssignedID)
		}

		if it.Product.BuyerAssignedID != nil {
			if l.Item.Identities == nil {
				l.Item.Identities = make([]*org.Identity, 0)
			}
			l.Item.Identities = append(l.Item.Identities, &org.Identity{
				Code: cbc.Code(*it.Product.BuyerAssignedID),
			})
		}

		if it.Product.GlobalID != nil {
			if l.Item.Identities == nil {
				l.Item.Identities = make([]*org.Identity, 0)
			}
			l.Item.Identities = append(l.Item.Identities, &org.Identity{
				// This label corresponds to a code from the ISO 6523 ICD List. Mapping is not yet supported
				Ext: tax.Extensions{
					iso.ExtKeySchemeID: cbc.Code(it.Product.GlobalID.SchemeID),
				},
				Code: cbc.Code(it.Product.GlobalID.Value),
			})
		}

		if it.Product.Description != nil {
			l.Item.Description = strings.TrimSpace(*it.Product.Description)
		}

		if it.Product.Origin != nil {
			l.Item.Origin = l10n.ISOCountryCode(*it.Product.Origin)
		}

		if it.LineDoc != nil && len(it.LineDoc.Note) > 0 {
			l.Notes = make([]*org.Note, 0, len(it.LineDoc.Note))
			for _, note := range it.LineDoc.Note {
				n := &org.Note{}
				if note.Content != "" {
					n.Text = strings.TrimSpace(note.Content)
				}
				if note.SubjectCode != "" {
					n.Key = cbc.Key(note.SubjectCode)
				}
				l.Notes = append(l.Notes, n)
			}
		}

		if len(it.TradeSettlement.ApplicableTradeTax) > 0 {
			for i, tt := range it.TradeSettlement.ApplicableTradeTax {
				if tt.CategoryCode != "" {
					l.Taxes[i].Ext = tax.Extensions{
						untdid.ExtKeyTaxCategory: cbc.Code(tt.CategoryCode),
					}
					// Look up exemption reason code from header tax summary
					key := buildTaxCategoryKey(tt.TypeCode, tt.CategoryCode, tt.RateApplicablePercent)
					if info, ok := taxMap[key]; ok && info.exemptionReasonCode != "" {
						l.Taxes[i].Ext[cef.ExtKeyVATEX] = cbc.Code(info.exemptionReasonCode)
					}
				}
				if tt.RateApplicablePercent != "" {
					if !strings.HasSuffix(tt.RateApplicablePercent, "%") {
						tt.RateApplicablePercent += "%"
					}
					p, err := num.PercentageFromString(tt.RateApplicablePercent)
					if err != nil {
						return err
					}
					// Skip setting percent if it's 0% and tax category is not "Z" (zero-rated)
					if p.IsZero() && tt.CategoryCode != "Z" {
						continue
					}
					l.Taxes[i].Percent = &p
				}
			}
		}

		if len(it.TradeSettlement.AllowanceCharge) > 0 {
			l, err = getLineCharges(it.TradeSettlement.AllowanceCharge, l)
			if err != nil {
				return err
			}
		}

		if len(it.Product.Characteristics) > 0 {
			l.Item.Meta = make(cbc.Meta)
			for _, char := range it.Product.Characteristics {
				key := formatKey(char.Description)
				l.Item.Meta[key] = char.Value
			}
		}

		// BT-158: Item classification
		if it.Product.Classification != nil && it.Product.Classification.Code != nil {
			if l.Item.Identities == nil {
				l.Item.Identities = make([]*org.Identity, 0)
			}
			id := &org.Identity{
				Code: cbc.Code(it.Product.Classification.Code.Value),
			}
			if it.Product.Classification.Code.ListID != "" {
				id.Ext = tax.Extensions{
					iso.ExtKeySchemeID: cbc.Code(it.Product.Classification.Code.ListID),
				}
			}
			l.Item.Identities = append(l.Item.Identities, id)
		}

		// BT-132: Purchase order line reference
		if it.Agreement.OrderReference != nil && it.Agreement.OrderReference.LineID != "" {
			l.Order = cbc.Code(it.Agreement.OrderReference.LineID)
		}

		// BT-133: Line buyer accounting reference
		if it.TradeSettlement.AccountingAccount != nil && it.TradeSettlement.AccountingAccount.ID != "" {
			l.Cost = cbc.Code(it.TradeSettlement.AccountingAccount.ID)
		}

		lines = append(lines, l)
	}

	out.Lines = lines
	return nil
}

// getLineCharges parses inline charges and discounts from the CII document
func getLineCharges(alwcs []*AllowanceCharge, l *bill.Line) (*bill.Line, error) {
	for _, ac := range alwcs {
		if ac.ChargeIndicator.Value {
			c, err := goblNewLineCharge(ac)
			if err != nil {
				return nil, err
			}
			if l.Charges == nil {
				l.Charges = make([]*bill.LineCharge, 0)
			}
			l.Charges = append(l.Charges, c)
		} else {
			d, err := goblNewLineDiscount(ac)
			if err != nil {
				return nil, err
			}
			if l.Discounts == nil {
				l.Discounts = make([]*bill.LineDiscount, 0)
			}
			l.Discounts = append(l.Discounts, d)
		}
	}
	return l, nil
}

// calculateRequiredPrecision determines the decimal precision needed when
// dividing a price by a base quantity to avoid rounding errors.
func calculateRequiredPrecision(price, baseQuantity num.Amount) uint32 {
	priceExp := price.Exp()

	baseQtyNormalized := baseQuantity.Rescale(0)
	baseQtyFloat := math.Abs(float64(baseQtyNormalized.Value()))

	additionalDecimals := uint32(0)
	if baseQtyFloat > 1 {
		additionalDecimals = uint32(math.Ceil(math.Log10(baseQtyFloat)))
	}

	return priceExp + additionalDecimals
}
